FROM node:16

#CREAR UNA CARPETA DONDE ESTARA EL DIRECTORIO DE TRABAJO
WORKDIR /app

#COPIAR ARCHIVOS FUENTE
#Copiar todo (/*) en el directorio actual (/app)
COPY . .

RUN npm install 

EXPOSE 80

#EJECUTAR UN COMANDO CON SUS PARAMETROS
CMD ["npm","start"]