version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.2
  aws-ecs: circleci/aws-ecs@3.0.0

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile
          path: ./
          profile-name: usuario-test
          region: us-east-1
          registry-id: ACCOUNT_ID
          repo: remember-repo
          tag: DJS-integration-remember

      - aws-ecs/deploy-service-update:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_DEFAULT_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          cluster: remember-repo-cluster
          container-image-name-updates: "container=remember-repo-container,tag=DJS-integration-remember"
          family: remember-repo-service
          profile-name: usuario-test
          requires:
            - aws-ecr/build-and-push-image
