version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - run: echo "Running tests"
      - run: npm install
      - run: npm unit
  build:
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - run: echo "Instalar dependencias e iniciar"
      - run: npm install
      - run: npm run start

workflows:
  test_build:
    jobs:
      - build
      - test:
        requires:
          - build