version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - run: echo "Running tests"
      - run: npm install
      - run: npm unit
  build:
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - run: echo "Instalar dependencias y correr pruebas"
      - run: npm install
      - run: npm run unit

workflows:
  test_build:
    jobs:
      - build