version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.2
  aws-ecs: circleci/aws-ecs@3.0.0
  aws-cli: circleci/aws-cli@3.1.1

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_ACCESS_SECRET
          create-repo: true
          dockerfile: Dockerfile
          path: ./
          profile-name: usuario-test
          region: us-east-1
          registry-id: ACCOUNT_ID
          repo: '${MY_APP_PREFIX}'
          tag: '${CIRCLE_SHA1}'

      - aws-ecs/deploy-service-update:
          cluster: "${MY_APP_PREFIX}-cluster"
          container-image-name-updates: "container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}"
          family: "${MY_APP_PREFIX}-service"
          requires:
            - aws-ecr/build-and-push-image
