version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.2
  aws-ecs: circleci/aws-ecs@3.0.0
  aws-cli: circleci/aws-cli@3.1.1

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_ACCESS_SECRET
          create-repo: true
          dockerfile: Dockerfile
          path: ./
          profile-name: usuario-test
          region: us-east-1
          registry-id: ACCOUNT_ID
          repo: remember-repo
          tag: abc

      - aws-ecs/deploy-service-update:
          cluster: arn:aws:ecs:us-east-1:983670070948:cluster/remember-repo-cluster
          container-image-name-updates: "container=remember-repo-container,tag=abc"
          family: "remember-repo-service"
          requires:
            - aws-ecr/build-and-push-image
